COMMENT =	suomi-français FreeDict+WikDict dictionary ver. 2022.11.18
DICT =	fin-fra
V =	2022.11.18

# Creative Commons Attribution-ShareAlike 3.0
PERMIT_PACKAGE =	Yes

.include "../Makefile.inc"
.include <bsd.port.mk>
