COMMENT =	Swahili-Polish SSSP/FreeDict Dictionary ver. 0.2.3
DICT =	swh-pol
V =	0.2.3

# GNU Free Documentation License 1.1 and GPLv3+
PERMIT_PACKAGE =	Yes

.include "../Makefile.inc"
.include <bsd.port.mk>
