# XXX: comment lookup in dict
# XXX: license?
COMMENT =	free bilingual dictionary
DICT =	deu-swe
V =	2022.11.18

# GPLv2 or v3 or CC-XYZ or no real license or fuck
PERMIT_PACKAGE =	Yes # XXX
#PERMIT_DISTFILES =	Yes | Reason if No

.include "../Makefile.inc"
.include <bsd.port.mk>
