COMMENT =	français-lietuvių kalba FreeDict+WikDict dictionary ver. 2022.11.18
DICT =	fra-lit
V =	2022.11.18

# Creative Commons Attribution-ShareAlike 3.0
PERMIT_PACKAGE =	Yes

.include <bsd.port.mk>
