# XXX: comment lookup in dict
# XXX: license?
COMMENT =	free bilingual dictionary
DICT =	oci-cat
V =	0.1.1

# GPLv2 or v3 or CC-XYZ or no real license or fuck
PERMIT_PACKAGE =	Yes # XXX
#PERMIT_DISTFILES =	Yes | Reason if No

.include "../Makefile.inc"
.include <bsd.port.mk>
