COMMENT =	Nederlands-lietuvių kalba FreeDict+WikDict dictionary ver. 2020.10.04
DICT =	nld-lit
V =	2020.10.04

# Creative Commons Attribution-ShareAlike 3.0
PERMIT_PACKAGE =	Yes

.include "../Makefile.inc"
.include <bsd.port.mk>
