COMMENT =	Deutsch-Bahasa Indonesia FreeDict+WikDict dictionary ver. 2022.11.18
DICT =	deu-ind
V =	2022.11.18

# Creative Commons Attribution-ShareAlike 3.0
PERMIT_PACKAGE =	Yes

.include <bsd.port.mk>
