COMMENT =	français-Русский FreeDict+WikDict dictionary ver. 2022.11.18
DICT =	fra-rus
V =	2022.11.18

# Creative Commons Attribution-ShareAlike 3.0
PERMIT_PACKAGE =	Yes

.include "../Makefile.inc"
.include <bsd.port.mk>
