COMMENT =	język polski-Nederlands FreeDict+WikDict dictionary ver. 2022.11.18
DICT =	pol-nld
V =	2022.11.18

# Creative Commons Attribution-ShareAlike 3.0
PERMIT_PACKAGE =	Yes

.include "../Makefile.inc"
.include <bsd.port.mk>
