COMMENT =		Python 2 and 3 compatibility library

MODPY_EGG_VERSION =	1.16.0
DISTNAME =		six-${MODPY_EGG_VERSION}

CATEGORIES =		devel

HOMEPAGE =		https://github.com/benjaminp/six
MAINTAINER =		Moritz Buhl <mbuhl@openbsd.org>

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_PYBUILD =		setuptools

.include <bsd.port.mk>
