COMMENT =	Nederlands-język polski FreeDict+WikDict dictionary ver. 2022.11.18
DICT =	nld-pol
V =	2022.11.18

# Creative Commons Attribution-ShareAlike 3.0
PERMIT_PACKAGE =	Yes

.include <bsd.port.mk>
