# $OpenBSD: Makefile.template,v 1.83 2019/07/02 12:03:14 sthen Exp $
#
# Replace ??? with appropriate values
# Remove extraneous comments before commit
# Use /usr/ports/infrastructure/bin/portcheck

COMMENT =	bash process with separate process group id
DISTNAME =	bash_process-1.2.3
CATEGORIES =	shells
HOMEPAGE =	https://isabelle.in.tum.de/
MAINTAINER =	Moritz Buhl <mbuhl@moritzbuhl.de>

# BSD
PERMIT_PACKAGE =	Yes
MASTER_SITES =		https://isabelle.in.tum.de/dist/contrib/
#SEPARATE_BUILD =	Yes # XXX
CONFIGURE_STYLE =	simple
CONFIGURE_SCRIPT =	build

.include <bsd.port.mk>
