COMMENT =	Nederlands-italiano FreeDict+WikDict dictionary ver. 2018.09.13
DICT =	nld-ita
V =	2018.09.13

# Creative Commons Attribution-ShareAlike 3.0
PERMIT_PACKAGE =	Yes

.include "../Makefile.inc"
.include <bsd.port.mk>
