# XXX: comment lookup in dict
# XXX: license?
COMMENT =	free bilingual dictionary
DICT =	eng-deu
V =	1.9-fd1

PKGNAME = freedict-${DICT}-${V:S/-fd1//}.dictd

# GPLv2 or v3 or CC-XYZ or no real license or fuck
PERMIT_PACKAGE =	Yes # XXX
#PERMIT_DISTFILES =	Yes | Reason if No

.include "../Makefile.inc"
.include <bsd.port.mk>
