COMMENT =	Japanese-German FreeDict Dictionary ver. 0.2.0
DICT =	jpn-deu
V =	0.2.0

# Creative Commons Attribution-ShareAlike 3.0
PERMIT_PACKAGE =	Yes

.include "../Makefile.inc"
.include <bsd.port.mk>
