COMMENT =		simplify exif manipulations with Python

MODPY_EGG_VERSION =	1.1.3
DISTNAME =		piexif-${MODPY_EGG_VERSION}
EXTRACT_SUFX =		.zip

CATEGORIES =		multimedia

HOMEPAGE =		https://github.com/hMatoba/Piexif
MAINTAINER =		Moritz Buhl <mbuhl@openbsd.org>

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_PYBUILD =		setuptools

.include <bsd.port.mk>
