COMMENT =	français-Türkçe FreeDict+WikDict dictionary ver. 2018.09.13
DICT =	fra-tur
V =	2018.09.13

# Creative Commons Attribution-ShareAlike 3.0
PERMIT_PACKAGE =	Yes

.include "../Makefile.inc"
.include <bsd.port.mk>
