COMMENT =	Nederlands-Bahasa Indonesia FreeDict+WikDict dictionary ver. 2022.04.06
DICT =	nld-ind
V =	2022.04.06

# Creative Commons Attribution-ShareAlike 3.0
PERMIT_PACKAGE =	Yes

.include <bsd.port.mk>
