# XXX: comment lookup in dict
# XXX: license?
COMMENT =	free bilingual dictionary
DICT =	nld-ind
V =	2022.04.06

# GPLv2 or v3 or CC-XYZ or no real license or fuck
PERMIT_PACKAGE =	Yes # XXX
#PERMIT_DISTFILES =	Yes | Reason if No

.include "../Makefile.inc"
.include <bsd.port.mk>
