COMMENT =	English - Modern Greek XDXF/FreeDict dictionary ver. 0.1.1
DICT =	eng-ell
V =	0.1.1

# GPLv2+ or Creative Commons BY-SA 3.0
PERMIT_PACKAGE =	Yes

.include "../Makefile.inc"
.include <bsd.port.mk>
