COMMENT =	English - Polish Piotrowski+Saloni/FreeDict dictionary ver. 0.2
DICT =	eng-pol
V =	0.2

# GPLv3+ and GNU Free Documentation License 1.2+
PERMIT_PACKAGE =	Yes

.include "../Makefile.inc"
.include <bsd.port.mk>
