# $OpenBSD$
#
COMMENT =	generic proof assistant
PKGNAME =	Isabelle
DISTNAME =	${PKGNAME}2020
CATEGORIES =	devel
HOMEPAGE =	https://isabelle.in.tum.de/
MAINTAINER =	Moritz Buhl <mbuhl@moritzbuhl.de>

# BSD
PERMIT_PACKAGE =	Yes
MASTER_SITES =		https://isabelle.in.tum.de/dist/
#SEPARATE_BUILD =	Yes # XXX
CONFIGURE_STYLE =	simple
CONFIGURE_SCRIPT =	build

.include <bsd.port.mk>
